services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    networks:
      - mongo-net
 
  cassandra-seed:
    image: cassandra:4.1
    container_name: mathews-cassandra-seed
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=mathews_cluster
      - CASSANDRA_SEEDS=mathews-cassandra-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Xms512M -Xmx512M
    volumes:
      - cassandra_seed_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - mongo-net
 
  cassandra-node2:
    image: cassandra:4.1
    container_name: mathews-cassandra-node2
    ports:
      - "9142:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=mathews_cluster
      - CASSANDRA_SEEDS=mathews-cassandra-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Xms512M -Xmx512M
    volumes:
      - cassandra_node2_data:/var/lib/cassandra
    depends_on:
      cassandra-seed:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - mongo-net
 
  cassandra-node3:
    image: cassandra:4.1
    container_name: mathews-cassandra-node3
    ports:
      - "9242:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=mathews_cluster
      - CASSANDRA_SEEDS=mathews-cassandra-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - JVM_OPTS=-Xms512M -Xmx512M
    volumes:
      - cassandra_node3_data:/var/lib/cassandra
    depends_on:
      cassandra-node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - mongo-net
 
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "configrs",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    volumes:
      - configsvr1_data:/data/db
    ports:
      - "27019:27017"
    networks:
      - mongo-net
 
  shard1-primary:
    image: mongo:latest
    container_name: shard1-primary
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1rs",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    volumes:
      - shard1_primary_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - mongo-net
 
  shard1-secondary:
    image: mongo:latest
    container_name: shard1-secondary
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1rs",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    volumes:
      - shard1_secondary_data:/data/db
    networks:
      - mongo-net
 
  shard1-arbiter:
    image: mongo:latest
    container_name: shard1-arbiter
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1rs",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    volumes:
      - shard1_arbiter_data:/data/arb
    networks:
      - mongo-net
 
  mongos:
    image: mongo:latest
    container_name: mongos
    command:
      [
        "mongos",
        "--configdb",
        "configrs/configsvr1:27017",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    depends_on:
      - configsvr1
      - shard1-primary
      - shard1-secondary
      - shard1-arbiter
 
  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    restart: "no"
    networks:
      - mongo-net
    depends_on:
      - mongos
    command: >
      bash -c "
        echo 'Esperando que los nodos estén listos...' &&
        sleep 15 &&
 
        echo '1/3 Inicializando Config Server RS...' &&
        mongosh --host configsvr1 --port 27017 --eval '
          rs.initiate({
            _id: \"configrs\",
            configsvr: true,
            members: [{ _id: 0, host: \"configsvr1:27017\" }]
          })
        ' &&
        sleep 5 &&
 
        echo '2/3 Inicializando Shard 1 RS (primary + secondary + arbiter)...' &&
        mongosh --host shard1-primary --port 27017 --eval '
          rs.initiate({
            _id: \"shard1rs\",
            members: [
              { _id: 0, host: \"shard1-primary:27017\"   },
              { _id: 1, host: \"shard1-secondary:27017\" },
              { _id: 2, host: \"shard1-arbiter:27017\", arbiterOnly: true }
            ]
          })
        ' &&
        sleep 15 &&
 
        echo '3/3 Registrando shard y habilitando sharding en mathews_coffee_delivery...' &&
        mongosh --host mongos --port 27017 --eval '
          db.adminCommand({ setDefaultRWConcern: 1, defaultWriteConcern: { w: 1 } });
          sh.addShard(\"shard1rs/shard1-primary:27017,shard1-secondary:27017\");
          sh.enableSharding(\"mathews_coffee_delivery\");
          sh.shardCollection(\"mathews_coffee_delivery.orders\", { region: 1 });
        ' &&
 
        echo 'Cluster inicializado correctamente.'
      "
 
  mongo-backup:
    image: weseek/mongodb-awesome-backup:latest
    container_name: mongo_backup
    restart: unless-stopped
    environment:
      - MONGODB_HOST=mongos
      - MONGODB_PORT=27017
      - TARGET_BUCKET_URL=gs://backups_cassandra/
      - GCP_SERVICE_ACCOUNT_KEY_JSON_PATH=/keys/gcp-key.json
      - GCP_PROJECT_ID=mathews-coffe
      - BACKUPFILE_PREFIX=backup-proyecto
      - CRONMODE=true
      - CRON_EXPRESSION=*/5 * * * *
    volumes:
      - ./backups:/backups
      - ./credentials/gcp-key.json:/keys/gcp-key.json:ro
    networks:
      - mongo-net
    depends_on:
      - mongos
 
 
  # CORREGIDO: BACKUPS DE CASSANDRA PARA GCS
 
  cassandra-backup:
    image: google/cloud-sdk:alpine
    container_name: cassandra_gcs_backup
    restart: unless-stopped
    volumes:
      - cassandra_seed_data:/var/lib/cassandra:ro
      - ./credentials/gcp-key.json:/keys/gcp-key.json:ro
      - ./gcs-backup.sh:/usr/local/bin/gcs-backup.sh:ro
    networks:
      - mongo-net
    environment:
      - GCS_BUCKET=backups_cassandra
      - GCP_PROJECT_ID=mathews-coffe
    command: >
      sh -c "
        echo 'Configurando el planificador de tareas...'
        
        # Aseguramos que el script tenga permisos de ejecución internos
        chmod +x /usr/local/bin/gcs-backup.sh

        # Configuramos el CRON nativo de Alpine para ejecutarlo cada 5 min
        echo '*/5 * * * * /usr/local/bin/gcs-backup.sh' > /etc/crontabs/root
        
        # Iniciamos el demonio de cron en primer plano
        crond -f -l 2
      "
    depends_on:
      cassandra-seed:
        condition: service_healthy
 
networks:
  mongo-net:
    driver: bridge
 
volumes:
  cassandra_seed_data:
  cassandra_node2_data:
  cassandra_node3_data:
  configsvr1_data:
  shard1_primary_data:
  shard1_secondary_data:
  shard1_arbiter_data: